### ISSUE TITLE
Als jurist wil ik meerdere verordeningen binnen het systeem kunnen beheren zodat ik een compleet nieuwe verordening kan aanmaken en de huidige kan bewerken

### ISSUE THREAD

**Issue by Swendude** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#316]
Is het wel één beheerder voor de complete verordening, is het niet gewoon dezelfde filosofie als bij de visie. - Marten Terpstra

**Comment by copebo** [comment]
**User story**
Als jurist wil ik meerdere verordeningen binnen het systeem kunnen beheren zodat ik een compleet nieuwe verordening kan aanmaken en de huidige kan bewerken

**Acceptatiecriteria/Specificaties**
- [ ] Ik kan een verordening aanmaken
- [ ] Ik kan een verordening wijzigen
- [ ] Ik kan een verordening archiveren ("verwijderen")

**Subtaken**
- [ ] Taak 1

**Comment by EVerhaar** [comment]
Voor een jurist is dit (nog) niet mogelijk; daarnaast staat de verordening alleen onder het kopje beheer. Ik ga na wie een nieuwe verordening moet kunnen aanmaken/wijzigen/archiveren.
