### ISSUE TITLE
Als jurist wil ik de onderdelen binnen een verordening kunnen muteren zodat ik de verordening gestructureerd kan opslaan

### ISSUE THREAD

**Issue by Swendude** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#317]

**Comment by copebo** [comment]
**User story**
Als jurist wil ik de onderdelen binnen een verordening kunnen muteren zodat ik de verordening gestructureerd kan opslaan

**Acceptatiecriteria/Specificaties**
- [ ] Hoofdstuk
    - [ ] Ik kan een hoofdstuk binnen een verordening aanmaken
    - [ ] Ik kan een hoofdstuk binnen een verordening wijzigen
        - [ ] Ik kan hoofdstuknummer invoeren (numeriek veld *)
        - [ ] Ik de titel aanpassen (tekstveld zonder limiet *)
        - [ ] Ik de inwerkingtredingdatum aanpassen (datum veld)
    - [ ] Ik kan de positie van een hoofdstuk binnen een verordening wijzigen (drag & drop)
    - [ ] Ik kan een hoofdstuk verwijderen
        - [ ] Als ik een hoofdstuk verwijder wil ik de optie krijgen om de inhoud te verwijderen
        - [ ] Als ik een hoofdstuk verwijder wil ik de optie krijgen om de inhoud onder een ander hoofdstuk onder te brengen

**Subtaken**
- [ ] Taak 1
