### ISSUE TITLE
Hoofdstuk: Als jurist wil ik een hoofdstuk kunnen toevoegen zodat ik de verordening kan structureren

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#336]
**User story**
Als jurist wil ik een hoofdstuk kunnen toevoegen zodat ik de verordening kan structureren

**Feature**
Hoofdstuk

**Acceptatiecriteria/Specificaties**
- [x] Ik kan een hoofdstuknummer invoeren (numeriek veld *)
- [x] Ik kan een titel invullen (tekstveld zonder limiet *)
- [x] Ik kan een inwerkingtredingsdatum invullen (datum veld)
    - [x] Ik kan de datum selecteren m.b.v. een _datepicker_
- [x] Ik kan de pagina verlaten zonder op te slaan
- [x] Ik kan het hoofdstuk opslaan

**Subtaken**
- [x] 1

**Comment by EVerhaar** [comment]
Moeten nummers en titels verplichte velden zijn? (Geldt ook voor afdelingen, paragrafen en artikels)
