### ISSUE TITLE
Hoofdstuk: Als jurist wil ik een hoofdstuk kunnen wijzigen zodat ik de titel kan aanpassen

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#337]
**User story**
Als jurist wil ik een hoofdstuk kunnen wijzigen zodat ik de titel kan aanpassen

**Feature**
Hoofdstuk

**Acceptatiecriteria/Specificaties**
- [x] Ik kan een hoofdstuknummer aanpassen (numeriek veld *)
- [x] Ik kan een titel aanpassen (tekstveld zonder limiet *)
- [x] Ik kan een inwerkingtredingsdatum aanpassen (datum veld)
    - [x] Ik kan de datum selecteren m.b.v. een _datepicker_
- [x] Ik kan de pagina verlaten zonder op te slaan
- [x] Ik kan het hoofdstuk opslaan

**Subtaken**
- [x] 1
