### ISSUE TITLE
Afdeling: Als jurist wil ik een afdeling kunnen toevoegen zodat ik de verordening kan structureren

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#338]
**User story**
Als jurist wil ik een afdeling kunnen toevoegen zodat ik de verordening kan structureren

**Feature**
Afdeling

**Acceptatiecriteria/Specificaties**
- [x] Ik kan een afdeling-nummer invoeren (numeriek veld *)
- [x] Ik kan een titel invullen (tekstveld zonder limiet *)
- [x] Ik kan een inwerkingtredingsdatum invullen (datum veld)
    - [x] Ik kan de datum selecteren m.b.v. een _datepicker_
- [x] Ik kan de pagina verlaten zonder op te slaan
- [x] Ik kan de afdeling opslaan

**Subtaken**
- [x] 1
