### ISSUE TITLE
Afdeling: Als jurist wil ik een afdeling kunnen wijzigen zodat ik de titel kan aanpassen

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#339]
**User story**
Als jurist wil ik een afdeling kunnen wijzigen zodat ik de titel kan aanpassen

**Feature**
Afdeling

**Acceptatiecriteria/Specificaties**
- [x] Ik kan een afdeling-nummer aanpassen (numeriek veld *)
- [x] Ik kan een titel aanpassen (tekstveld zonder limiet *)
- [x] Ik kan een inwerkingtredingsdatum aanpassen (datum veld)
    - [x] Ik kan de datum selecteren m.b.v. een _datepicker_
- [x] Ik kan de pagina verlaten zonder op te slaan
- [x] Ik kan de afdeling opslaan

**Subtaken**
- [x] 1
