### ISSUE TITLE
Paragraaf: Als jurist wil ik een paragraaf kunnen wijzigen zodat ik de titel en het nummer kan aanpassen

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#341]
**User story**
Als jurist wil ik een paragraaf kunnen wijzigen zodat ik de titel en het nummer kan aanpassen

**Feature**
Paragraaf

**Acceptatiecriteria/Specificaties**
- [x] Ik kan een paragraafnummer aanpassen (numeriek veld *)
- [x] Ik kan een titel aanpassen (tekstveld zonder limiet *)
- [x] Ik kan een inwerkingtredingsdatum aanpassen (datum veld)
    - [x] Ik kan de datum selecteren m.b.v. een _datepicker_
- [x] Ik kan de pagina verlaten zonder op te slaan
- [x] Ik kan de paragraaf opslaan

**Subtaken**
- [x] 1

**Comment by EVerhaar** [comment]
Moet men bij het verlaten van de pagina nog een melding krijgen 'weet u zeker dat u terug wil naar het overzicht? Niet opgeslagen gegevens gaan hierbij verloren'?
