### ISSUE TITLE
Artikel: Als jurist wil ik een artikel kunnen toevoegen aan de verordening zodat ik de inhoud van de verordening gestructureerd kan plaatsen

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#342]
**User story**
Als jurist wil ik een artikel kunnen toevoegen aan de verordening zodat ik de inhoud van de verordening gestructureerd kan plaatsen

**Feature**
Artikel

**Acceptatiecriteria/Specificaties**
- [x] Ik kan een artikelnummer invullen (numeriek veld *)
- [x] Ik kan de titel invullen (tekstveld zonder limiet *)
- [x] Ik kan een ambtelijk opdrachtgever selecteren uit een lijst (select *)
- [x] Ik kan twee eigenaren selecteren uit een lijst met eigenaren (select *)
- [x] Ik kan twee portefeuillehouders selecteren uit een lijst (select *)
- [x] Ik kan de inhoud van het artikel invullen (text/wysiwyg *)
- [x] Ik kan een werkingsgebied selecteren uit een overzicht (*)
- [x] Ik kan een IDMS-link invullen (tekstveld zonder limiet *)
- [x] Ik kan de inwerkingtredingdatum invullen (datum veld)
- [x] Ik kan het uitwerkingtredingdatum verbergen/tonen
- [x] Ik kan de uitwerkingtredingdatum invullen (datum veld)
- [x] Ik kan de pagina verlaten zonder op te slaan
- [x] Ik kan het artikel opslaan

**Subtaken**
- [x] 1
