### ISSUE TITLE
Artikel: Als jurist wil ik een artikel kunnen wijzigen zodat ik aanpassingen aan de verordening kan aanbrengen

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#343]
**User story**
Als jurist wil ik een artikel kunnen wijzigen zodat ik aanpassingen aan de verordening kan aanbrengen

**Feature**
Artikel

**Acceptatiecriteria/Specificaties**
- [x] Ik kan een artikelnummer aanpassen (numeriek veld *)
- [x] Ik kan de titel aanpassen (tekstveld zonder limiet *)
- [x] Ik kan een ambtelijk opdrachtgever selecteren uit een lijst (select *)
- [x] Ik kan twee eigenaren selecteren uit een lijst met eigenaren (select *)
- [x] Ik kan twee portefeuillehouders selecteren uit een lijst (select *)
- [x] Ik kan de inhoud van het artikel aanpassen (text/wysiwyg *)
- [x] Ik kan een werkingsgebied selecteren uit een overzicht (*)
- [x] Ik kan een IDMS-link aanpassen (tekstveld zonder limiet *)
- [x] Ik kan de inwerkingtredingdatum aanpassen (datum veld)
- [x] Ik kan het uitwerkingtredingdatum verbergen/tonen
- [x] Ik kan de uitwerkingtredingdatum aanpassen (datum veld)
- [x] Ik kan de pagina verlaten zonder op te slaan
- [x] Ik kan het artikel opslaan

**Subtaken**
- [x] 1
