### ISSUE TITLE
Paragraaf: Als jurist wil ik een paragraaf kunnen verwijderen zodat deze niet meer in de verordening voorkomt

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#345]
**User story**
Als jurist wil ik een paragraaf kunnen verwijderen zodat deze niet meer in de verordening voorkomt

**Feature**
Paragraaf

**Acceptatiecriteria/Specificaties**
- [ ] Ik kan een paragraaf verwijderen
    - [ ] De paragraaf krijgt een nieuwe datum uitwerkingtreding 
- [ ] Een paragraaf kan pas worden verwijderd, als er geen artikelen meer aan gekoppeld zijn

**Subtaken**
- [ ] 1
