### ISSUE TITLE
Afdeling: Als jurist wil ik een afdeling kunnen verwijderen zodat deze niet meer in de verordening voorkomt

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#346]
**User story**
Als jurist wil ik een afdeling kunnen verwijderen zodat deze niet meer in de verordening voorkomt

**Feature**
Afdeling

**Acceptatiecriteria/Specificaties**
- [ ] Ik kan een afdeling verwijderen
    - [ ] De afdeling krijgt een nieuwe datum uitwerkingtreding 
- [ ] Een afdeling kan pas worden verwijderd, als er geen paragraven en/of artikelen meer aan gekoppeld zijn

**Subtaken**
- [ ] 1
