### ISSUE TITLE
Hoofdstuk: Als jurist wil ik een hoofdstuk kunnen verwijderen zodat deze niet meer in de verordening voorkomt

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#347]
**User story**
Als jurist wil ik een hoofdstuk kunnen verwijderen zodat deze niet meer in de verordening voorkomt

**Feature**
Hoofdstuk

**Acceptatiecriteria/Specificaties**
- [ ] Ik kan een hoofdstuk verwijderen
    - [ ] Het hoofdstuk krijgt een nieuwe datum uitwerkingtreding 
- [ ] Het hoofdstuk kan pas worden verwijderd, als er geen afdelingen, paragraven en/of artikelen meer aan gekoppeld zijn

**Subtaken**
- [ ] 1

**Comment by EVerhaar** [comment]
Ik krijg in Chrome onderstaande melding; hier staat nog niet in dat alle onderliggende objecten ook verwijderd worden

![Screenshot20200214 - melding bij verwijderen in Chrome](https://user-images.githubusercontent.com/57626563/74517255-147d8f00-4f12-11ea-8916-b27df5c59d9d.PNG)
