### ISSUE TITLE
Drag & Drop: Als jurist wil ik de volgorde van de objecten binnen een hoofdstuk van de verordening kunnen aanpassen zodat ik hier een logische volgorde in kan aanbrengen

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#348]
**User story**
Als jurist wil ik de volgorde van de objecten binnen een hoofdstuk van de verordening kunnen aanpassen zodat ik hier een logische volgorde in kan aanbrengen

**Feature**
Drag & Drop

**Acceptatiecriteria/Specificaties**
- [x] Ik kan de volgorde van de afdelingen binnen een hoofdstuk aanpassen
- [x] Ik kan de volgorde van de paragraven binnen een hoofdstuk en binnen een afdeling aanpassen
- [x] Ik kan de volgorde van de artikelen aanpassen binnen een hoofdstuk, afdeling en paragraaf
- [x] Ik kan het aanpassen van de volgorde annuleren zodat alles weer terugvalt naar de originele positie

**Subtaken**
- [x] Taak 1
