### ISSUE TITLE
Accounts: Als functioneel beheerder wil ik kunnen zoeken in de lijst met gebruikers zodat ik snel de accountgegevens van een gebruiker kan zien

### ISSUE THREAD

**Issue by EVerhaar** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#353]
**User story**
Accounts: Als functioneel beheerder wil ik kunnen zoeken in de lijst met gebruikers zodat ik snel de accountgegevens van een gebruiker kan zien

**Acceptatiecriteria/Specificaties**
- [ ] Zoekfunctie werkt naar behoren
    - [ ] Lijst met alle gebruikers is zichtbaar
    - [ ] Zoeken op naam werkt
    - [ ] Filteren op rol is mogelijk
    - [ ] Zoeken op UUID is mogelijk
