### ISSUE TITLE
Accounts: Als functioneel beheerder wil ik de rol van een gebruiker kunnen wijzigen zodat gebruikers beleid wel/niet kunnen muteren als ze een andere functie krijgen

### ISSUE THREAD

**Issue by EVerhaar** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#354]
**User story**
Accounts: Als functioneel beheerder wil ik de gegevens van een gebruiker kunnen wijzigen zodat gebruikers er geen oude of verkeerde gegevens in de database staan.

**Acceptatiecriteria/Specificaties**
- [ ] Rol van gebruikers kan worden aangepast
- [ ] Naam van gebruiker kan worden aangepast
- [ ] Gebruiker kan worden geselecteerd
    - [ ] Werkende button 'bewerken'

**Subtaken**
Rollen:
    - [ ] Administrator
    - [ ] Beheerder
    - [ ] Muteerder
    - [ ] Opdrachtgever
    - [ ] Portefeuillehouder
    - [ ] Raadpleger
