### ISSUE TITLE
Als jurist wil ik de nummers binnen de verordening zelf kunnen invoeren zodat ik zelf controle hou over de nummers van de onderdelen van de verordening

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#363]
**User story**
Als jurist wil ik de nummers binnen de verordening zelf kunnen invoeren zodat ik zelf controle hou over de nummers van de onderdelen van de verordening

**Acceptatiecriteria/Specificaties**
- [ ] Ik kan een hoofdstuk voorzien van een nummer (incl. eventueel A, B, C, etc.)
- [ ] Ik kan een afdeling voorzien van een nummer, ik vul hier alleen het nummer in van de afdeling, die van het hoofdstuk moet het systeem zelf genereren/toevoegen bij het laten zien
- [ ] Ik kan een paragraaf voorzien van een nummer, ik vul hier alleen het nummer in van de paragraaf, die van het hoofdstuk (en eventuele afdeling) moet het systeem zelf genereren/toevoegen bij het laten zien
- [ ] Ik kan een artikel voorzien van een nummer,  ik vul hier alleen het nummer in van het artikel, die van het hoofdstuk (en eventuele afdeling) en paragraaf moet het systeem zelf genereren/toevoegen bij het laten zien

_Let op, met nummer bedoelen we overal 1, 2,3 maar ook 1A, 2C, etc._

**Comment by Aidenbuis** [comment]
>  Ik kan een artikel voorzien van een nummer, ik vul hier alleen het nummer in van het artikel, die van het hoofdstuk (en eventuele afdeling) en paragraaf moet het systeem zelf genereren/toevoegen bij het laten zien

Een afdeling wordt niet meegenomen in de nummering van een artikel toch? Dit is enkel het hoofdstuk wat ervoor komt?

![image](https://user-images.githubusercontent.com/9105359/74918115-eba14200-53c8-11ea-9bce-ae9b7bb44445.png)

**Comment by copebo** [comment]
De nummering van de verordening is als volgt:

**Hoofdstuk**
Zelf in te vullen nummer (plus eventueel A, B, etc.)
Voorbeeld: Hoofdstuk 3

**Afdeling**
Het nummer van het bovenliggende hoofdstuk + Zelf in te vullen nummer (plus eventueel A, B, etc.)
Voorbeeld: Afdeling 3.1

**Paragraaf**
Het nummer van het bovenliggende hoofdstuk + ( als er een afdeling bestaat het nummer van de bovenliggende afdeling +) Zelf in te vullen nummer (plus eventueel A, B, etc.)
Voorbeeld 1: § 3.2
Voorbeeld 2: § 3.1.2

**Artikel**
Voor zover nu bekend, krijgt een artikel een compleet eigen nummering (los van hoofdstuk, afdeling en paragraaf). Dus gewoon "Artikel 24" (eventueel met A, B, etc.)
