### ISSUE TITLE
Als jurist wil ik de verplichte velden zien bij het aanmaken of aanpassen van een hoofdstuk/afdeling/paragraaf/artikel zodat ik duidelijk zie waarom ik niet kan opslaan

### ISSUE THREAD

**Issue by EVerhaar** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#369]
**User story**
Als jurist wil ik de verplichte velden zien bij het aanmaken of aanpassen van een hoofdstuk/afdeling/paragraaf/artikel zodat ik duidelijk zie waarom ik niet kan opslaan

**Acceptatiecriteria/Specificaties**
- [ ] Ik zie de verplichte velden bij het aanmaken van een hoofdstuk
- [ ] Ik zie de verplichte velden bij het wijzigen van een hoofdstuk
- [ ] Ik zie de verplichte velden bij het aanmaken van een afdeling
- [ ] Ik zie de verplichte velden bij het wijzigen van een afdeling
- [ ] Ik zie de verplichte velden bij het aanmaken van een paragraaf
- [ ] Ik zie de verplichte velden bij het wijzigen van een paragraaf
- [ ] Ik zie de verplichte velden bij het aanmaken van een artikel
- [ ] Ik zie de verplichte velden bij het wijzigen van een artikel
