### ISSUE TITLE
Als raadpleger wil ik niet buiten de grenzen van Zuid-Holland een marker kunnen neerzetten zodat ik niet de verwachting krijg dat ik beleid van andere provincies kan inzien.

### ISSUE THREAD

**Issue by EVerhaar** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#374]
**User story**
Als raadpleger wil ik niet buiten de grenzen van Zuid-Holland een marker kunnen neerzetten zodat ik niet de verwachting krijg dat ik beleid van andere provincies kan inzien.

**Acceptatiecriteria/Specificaties**
- [ ] Het is niet mogelijk om buiten de grenzen van Zuid-Holland een marker neer te zetten
- [ ] Het is niet mogelijk om een marker buiten ZH te verplaatsen
- [ ] Het is niet mogelijk om een gebied buiten de grenzen van ZH te tekenen
- [ ] Het is niet mogelijk om de grenzen van een gebied te verplaatsen buiten de grenzen van ZH
