### ISSUE TITLE
Navigatie verordening in raadpleegomgeving

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#386]
**User story**
Als gebruiker wil ik een overzicht van de onderdelen in binnen de verordening zodat ik eenvoudig kan navigeren door de verordening

**Acceptatiecriteria/Specificaties**
Tonen:
- [x] Ik zie een overzicht van hoofdstukken
- [x] Ik zie een overzicht van de afdelingen binnen het geselecteerd hoofdstuk (mits er afdelingen zijn)
- [x] Ik zie een overzicht van de paragraven binnen de geselecteerde afdeling (mits er paragraven zijn)
- [x] Ik zie een overzicht van de artikelen binnen het geselecteerde paragraaf/afdeling/hoofdstuk
- [x] Het huidige artikel is dik gedrukt in het overzicht

Werking:
- [x] Er kan maximaal 1 hoofdstuk, afdeling of paragraaf "open" staan

Klikken:
- [x] Zodra ik een hoofdstuk aanklik, klappen alle hoofdstukken dicht, behalve het aangeklikte hoofdstuk, die klapt open.
- [x] Zodra ik een afdeling aanklik, klappen alle afdelingen dicht, behalve de aangeklikte afdeling, die klapt open.
- [x] Zodra ik een paragraaf aanklik, klappen alle paragraven dicht, behalve de aangeklikte paragraaf, die klapt open.
- [x] Zodra ik een artikel aanklik, ga ik naar het geselecteerde artikel

![Artikel - Detail (Sidebar)](https://user-images.githubusercontent.com/54364210/76312564-9f646600-62d3-11ea-874d-72a0712acccd.jpg)
