### ISSUE TITLE
DNS van obzh.nl

### ISSUE THREAD

**Issue by copebo** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#388]
**Taken**
- [x] Zorgen dat test.obzh.nl doorlinkt naar https://obzhtest.azureedge.net/
- [x] Zorgen dat acc.obzh.nl doorlinkt naar https://obzhacc.azureedge.net/
- [x] Zorgen dat www.obzh.nl doorlinkt naar https://`subdomein`.zuid-holland.nl/
- [x] Zorgen dat https://`subdomein`.zuid-holland.nl/ doorlinkt naar https://obzhprod.azureedge.net/ 

- [x] Officieel SSL Certificaat regelen voor `subdomein`.zuid-holland.nl

Afhankelijk van #387
