### ISSUE TITLE
Ervoor zorgen dat eigenaren hun beleidskeuzes kunnen aanpassen

### ISSUE THREAD

**Issue by HagenaarC** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#451]
**User story**
Als eigenaar wil ik mijn beleidskeuzes kunnen aanpassen om deze actueel te houden.

**Feature**
Aanpassen van beleidskeuzes

**Acceptatie criteria**
- [ ] Alleen de eigenaar kan een beleidskeuze wijzigen
- [ ] Alleen de eigenaar kan een beleidskeuze toevoegen
- [ ] Alleen de eigenaar kan een beleidskeuze verwijderen
