### ISSUE TITLE
Velden beleidskeuzes herzien

### ISSUE THREAD

**Issue by HagenaarC** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#452]
**User story** 
Als gebruiker wil ik een nieuw invulformulier voor beleidskeuzes die overeenkomt met nieuwe volgorde en terminologie zodat mijn keuze daarop aansluit. 

**Feature**
Aanpassen van beleidskeuzes

**Acceptatie criteria**
- [ ] Formulier bevat de volgende velden:
  - [ ] Titel (tekstveld, verplicht)
  - [ ] Opdrachtgever (dropdown, verplicht, typen om te filteren) 
  - [ ] Eerste eigenaar (dropdown, verplicht, typen om te filteren) 
  - [ ] Tweede eigenaar (dropdown, verplicht, typen om te filteren) 
  - [ ] Eerste portefeuillehouder (dropdown, verplicht, typen om te filteren) 
  - [ ] Tweede portefeuillehouder (dropdown, verplicht, typen om te filteren) 
  - [ ] Aanleiding (tekstveld, verplicht) 
  - [ ] Provinciaal belang (tekstveld, verplicht) 
  - [ ] Koppelen nationale belang en wettelijke taken en bevoegdheden (optioneel) 
  - [ ] Toelichting (tekstveld, verplicht)
  - [ ] Werkingsgebied (verplicht)
  - [ ] Koppelingen relaties andere beleidskeuzes (optioneel)
