### ISSUE TITLE
Maatregelen opstellen

### ISSUE THREAD

**Issue by HagenaarC** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#456]
**User story**
Als behandelend ambtenaar wil ik een maatregel kunnen toevoegen in het systeem. 

**Feature**
Aanpassen van maatregelen

**Acceptatiecriteria/Specificaties**
- [ ] De BA kan een maatregel aanmaken
- [ ] De BA moet een titel invoeren
   - [ ] Maximaal 10 woorden
- [ ] Toelichtingsveld 
   - [ ] Met rolkeuze
- [ ] De BA kan een werkingsgebied selecteren (verplicht)
- [ ] De fase van een maatregel wordt bijgehouden (concept, ontwerp, inspraak, besluitvorming, vigerend) 
- [ ] Fase van de maatregel is alleen zichtbaar in de muteeromgeving <br>
- [ ] De beheerder moet een maatregel goedkeuren
  - [ ] verplicht invoeren inwerkingstreding
  - [ ] verplicht invoeren iDMS link naar besluit
 
**Ontwerp**
https://www.sketch.com/s/f8080aa1-cece-4b28-9a2f-adabe0aa7b3c/a/oz1WdD
