### ISSUE TITLE
Verbeteren structuur zoek-resultaten

### ISSUE THREAD

**Issue by HagenaarC** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#461]
**User story** 
Als raadpleger wil ik gebruiksvriendelijke zoekresultaten hebben die ingedeeld zijn in categorieën om zo mijn gewenste gewenste informatie in afzienbare tijd te vinden. 

**Feature**
Structuur zoeksresultaten verbeteren

**Acceptatie criteria**
- [ ] Wanneer ik zoek op een gemeente dan wordt niet een punt getoond, maar de hele gemeente
- [ ] De categorieën waar raadplegers op kunnen zoeken
     - [ ] Overzicht van wijzigingen:
- [ ] De structuur van de zoekresultaten die teruggegeven worden gebruiksvriendelijker maken
     - [ ] De structuur moet als volgt zijn:
