### ISSUE TITLE
Usertool overzetten naar test, acc en prod

### ISSUE THREAD

**Issue by EVerhaar** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#464]
**Taken**
Op dit moment werkt de usertool alleen op de dev database zodat we met de gegevens die in deze database stonden konden testen. Nu de usertool mvp-af is moet deze worden omgezet zodat:
- [x] De usertool gebruikt kan worden op de test-database
- [x] De usertool gebruikt kan worden op de acc-database
- [x] De usertool gebruikt kan worden op de prod-database
