### ISSUE TITLE
Gemeentegrenzen toevoegen aan raadpleegomgeving

### ISSUE THREAD

**Issue by EVerhaar** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#480]
**User story**
Als gebruiker wil ik de gemeentegrenzen zien op de kaart in de raadpleegomgeving zodat ik precies weet of bepaald beleid of regelgeving van de provincie van toepassing is binnen een bepaalde gemeente.

**Acceptatiecriteria/Specificaties**
- [ ] Gemeentegrenzen zijn zichtbaar op de kaart in de raadpleegomgeving door een outline
- [ ] De outline is subtieler dan de andere legenda items 
- [ ] Wanneer ik zoek op een gemeente dan wordt niet een punt getoond, maar de hele gemeente

**Subtaken**
- [ ] Taak 1
